<?php
use Drupal\field\Entity\FieldConfig;
use Drupal\field\Entity\FieldStorageConfig;
use Drupal\file\Entity\File;
use Drupal\Core\File\FileSystemInterface;
use Drupal\file\FileInterface;

/**
 *
 * @file
 * Primary module hooks for Export Import Entities module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

/**
 *
 * @param Drupal\Core\Entity\EntityInterface $entity
 */
function export_import_entities_field_storage_config_insert(FieldStorageConfig $FieldConfig) {
  if ($FieldConfig->get('type') == 'image') {
    \Stephane888\Debug\debugLog::symfonyDebug($FieldConfig->toArray(), $FieldConfig->id() . '_field_type', true);
    $settings = $FieldConfig->getSettings();
    if (!empty($settings['default_image']['uuid'])) {
      $uuid = $settings['default_image']['uuid'];
      $default_encode_file = $FieldConfig->get('default_encode_file');
      if (!empty($default_encode_file))
        if ($stream_file = fopen($default_encode_file, 'r')) {
          $filename = $FieldConfig->get('default_filename');
          /**
           *
           * @var \Drupal\Core\File\FileSystem $filesystem
           */
          $filesystem = \Drupal::service('file_system');
          $icon_upload_path = "public://export_import_entities__field_storage_config/";
          $icon_file_destination = $icon_upload_path . $filename;
          // Check the directory exists before writing data to it.
          $filesystem->prepareDirectory($icon_upload_path, FileSystemInterface::CREATE_DIRECTORY | FileSystemInterface::MODIFY_PERMISSIONS);
          // Save the default icon file.
          $file_uri = $filesystem->saveData($stream_file, $icon_file_destination);
          if ($file_uri) {
            // Create the file entity.
            $values = [
              'uri' => $file_uri,
              'uid' => \Drupal::currentUser()->id(),
              'uuid' => $uuid,
              'status' => FileInterface::STATUS_PERMANENT
            ];
            $file = File::create($values);
            $file->save();
            /** @var \Drupal\file\FileUsage\FileUsageInterface $file_usage */
            $file_usage = \Drupal::service('file.usage');
            // Add usage of the new icon file.
            $file_usage->add($file, 'field', 'field_config', $uuid);
          }
        }
    }
  }
}

/**
 *
 * @param Drupal\Core\Entity\EntityInterface $entity
 */
function export_import_entities_field_config_insert(FieldConfig $FieldConfig) {
  // recupere l'image encode par le module export_import_entities.
  if ($FieldConfig->get('field_type') == 'image') {
    \Stephane888\Debug\debugLog::symfonyDebug($FieldConfig->toArray(), $FieldConfig->id() . '_field_type', true);
    $settings = $FieldConfig->getSettings();
    if (!empty($settings['default_image']['uuid'])) {
      $uuid = $settings['default_image']['uuid'];
      $default_encode_file = $FieldConfig->get('default_encode_file');
      if (!empty($default_encode_file))
        if ($stream_file = fopen($default_encode_file, 'r')) {
          $filename = $FieldConfig->get('default_filename');
          /**
           *
           * @var \Drupal\Core\File\FileSystem $filesystem
           */
          $filesystem = \Drupal::service('file_system');
          $icon_upload_path = "public://export_import_entities__field_config/";
          $icon_file_destination = $icon_upload_path . $filename;
          // Check the directory exists before writing data to it.
          $filesystem->prepareDirectory($icon_upload_path, FileSystemInterface::CREATE_DIRECTORY | FileSystemInterface::MODIFY_PERMISSIONS);
          // Save the default icon file.
          $file_uri = $filesystem->saveData($stream_file, $icon_file_destination);
          if ($file_uri) {
            // Create the file entity.
            $values = [
              'uri' => $file_uri,
              'uid' => \Drupal::currentUser()->id(),
              'uuid' => $uuid,
              'status' => FileInterface::STATUS_PERMANENT
            ];
            $file = File::create($values);
            $file->save();
            /** @var \Drupal\file\FileUsage\FileUsageInterface $file_usage */
            $file_usage = \Drupal::service('file.usage');
            // Add usage of the new icon file.
            $file_usage->add($file, 'field', 'field_config', $uuid);
          }
        }
    }
  }
}